import { Router } from 'express';
import authRoutes from './authRoutes';
import userRoutes from './userRoutes';
import courseRoutes from './courseRoutes';
import lessonRoutes from './lessonRoutes';
import exerciseRoutes from './exerciseRoutes';
import serialKeyRoutes from './serialKeyRoutes';
import forumRoutes from './forumRoutes';
import statsRoutes from './statsRoutes';
import accessLogRoutes from './accessLogRoutes';
import examRoutes from './examRoutes';
import questionRoutes from './questionRoutes';
import siteConfigRoutes from './siteConfigRoutes';
import courseTopicRoutes from './courseTopicRoutes';
import courseSubtopicRoutes from './courseSubtopicRoutes';
import zoomRoutes from './zoomRoutes';
import announcementRoutes from './announcementRoutes';
import certificateRoutes from './certificateRoutes';
import certificateRequestRoutes from './certificateRequestRoutes';
import notesRoutes from './notesRoutes';
import paymentRoutes from './paymentRoutes';
import couponRoutes from './couponRoutes';
import priceLotRoutes from './priceLotRoutes';
import materialRoutes from './materialRoutes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/courses', courseRoutes);
router.use('/lessons', lessonRoutes);
router.use('/exercises', exerciseRoutes);
router.use('/serial-keys', serialKeyRoutes);
router.use('/forum', forumRoutes);
router.use('/stats', statsRoutes);
router.use('/access-logs', accessLogRoutes);
router.use('/exams', examRoutes);
router.use('/questions', questionRoutes);
router.use('/site-config', siteConfigRoutes);
router.use('/course-topics', courseTopicRoutes);
router.use('/course-subtopics', courseSubtopicRoutes);
router.use('/zoom', zoomRoutes);
router.use('/announcements', announcementRoutes);
router.use('/certificates', certificateRoutes);
router.use('/certificate-requests', certificateRequestRoutes);
router.use('/notes', notesRoutes);
router.use('/payments', paymentRoutes);
router.use('/coupons', couponRoutes);
router.use('/price-lots', priceLotRoutes);
router.use('/materials', materialRoutes);

export default router;

